name: "✨ Feature"
description: Request a feature
title: "[Feature] <title>"
labels: ["feature", "triage"]
# projects: []
# assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        Remember, contributions to this repository should follow its [contributing guidelines](../blob/develop/docs/CONTRIBUTING.md).
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you are requesting.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe The Problem
      description: Please present a concise description of the problem to be addressed by this feature request. Please be clear what parts of the problem are considered to be in-scope and out-of-scope.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggest A Solution
      description: |
        A concise description of your preferred solution. If there are multiple solutions, please present each one separately. Save comparisons for the very end.
      placeholder: |
        Things to address include:
        - Details of the technical implementation
        - Tradeoffs made in design decisions
        - Caveats and considerations for the future
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the feature you are requesting!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
