name: Codecov

on:
  push:
    branches: [main, develop, coverage]
  pull_request:
    types: [opened, synchronize]

jobs:
  unittests:
    name: Unit Tests Coverage
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.6.12

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Generate Reports
        run: pnpm coverage

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          name: ckb-cobuild
          fail_ci_if_error: true
          verbose: true
